### ISSUE TITLE
Add more operators

### ISSUE THREAD

**Issue by clemme** [eikooc/language-RSL#1]
Here is a suggestion to some additional keywords to the RSL
{
    'match': '\b(scheme|class|type|value|end|-set**|test_case|extend|with**)\b'
    'name': 'support.function.construct.rsl'
  }
Here is some suggestions to some of the additional build in functions
  {
    'match': '\b(let|-set|all|exists|is|in|isin**|inter|len|hd|abs|int|real|card|inds|elems|tl|dom|rng**)\b'
    'name': 'support.function.basic_functions.rsl'
  }

**Comment by eikooc** [comment]
Sorry didn't see you had posted an issue.
I will be right on it!

**Comment by eikooc** [comment]
v0.29.4 should now have these added.
